"""Resolved build-time configuration and runtime paths.

Prefers the Meson-generated ``_build`` module; falls back to source-checkout
defaults so the app and tools can run uninstalled (``python3 -m yonderloft.main``).
"""
from __future__ import annotations

import os

try:
    from . import _build  # generated by Meson
    APP_ID = _build.APP_ID
    VERSION = _build.VERSION
    PKGDATADIR = _build.PKGDATADIR
    LOCALEDIR = _build.LOCALEDIR
    INSTALLED = True
except ImportError:
    # Running from a source checkout.
    APP_ID = "uk.aaronworld.Yonderloft"
    VERSION = "0.1.0-dev"
    _repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    # In a checkout the bundled catalog lives at <repo>/catalog, not pkgdatadir.
    PKGDATADIR = _repo_root
    LOCALEDIR = os.path.join(_repo_root, "po")
    INSTALLED = False


def bundled_catalog_path() -> str:
    """Path to the manifest.json that ships with the app (offline seed)."""
    if INSTALLED:
        return os.path.join(PKGDATADIR, "catalog", "manifest.json")
    return os.path.join(PKGDATADIR, "catalog", "manifest.json")


def bundled_schema_path() -> str:
    if INSTALLED:
        return os.path.join(PKGDATADIR, "catalog", "schema.json")
    return os.path.join(PKGDATADIR, "catalog", "schema.json")


def cache_dir() -> str:
    from gi.repository import GLib  # lazy: keeps stdlib tools GTK-free
    path = os.path.join(GLib.get_user_cache_dir(), "yonderloft")
    os.makedirs(path, exist_ok=True)
    return path


def data_dir() -> str:
    from gi.repository import GLib  # lazy: keeps stdlib tools GTK-free
    path = os.path.join(GLib.get_user_data_dir(), "yonderloft")
    os.makedirs(path, exist_ok=True)
    return path
