name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install flatpak and flatpak-builder on the host machine
      - name: Install Flatpak dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Yonderloft.flatpak
          manifest-path: build-aux/flatpak/uk.aaronworld.Yonderloft.json
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            Yonderloft.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}